SYSTEM_NODE_SYSTEM = "System"
SYSTEM_NODE_PACKAGE = "Package"
SYSTEM_NODE_FILE = "CodeFile"
SYSTEM_NODE_SYMBOL = "Symbol"
SYSTEM_NODE_ARTIFACT = "Artifact"

EDGE_CONTAINS = "CONTAINS"
EDGE_DEFINES = "DEFINES"
EDGE_IMPORTS = "IMPORTS"
EDGE_BELONGS_TO = "BELONGS_TO"

SYSTEM_ROLE_PRIMARY = "primary"
SYSTEM_ROLE_RELATED = "related"

INGEST_STATUS_READY = "ready"
INGEST_STATUS_MISSING = "source_missing"
INGEST_STATUS_FAILED = "failed"
INGEST_STATUS_PENDING = "pending"

CONNECTOR_GENERIC_GIT = "generic_git"
CONNECTOR_METADATA_EXPORT = "metadata_export"

SOURCE_TYPE_GIT = "git"
SOURCE_TYPE_EXPORT = "export"
