apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regshift-ingress
spec:
  rules:
    - host: regshift.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: regshift-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: regshift-backend
                port:
                  number: 8000
